name: Sync with template

on:
  push:
    branches:
      - main

jobs:
  template-sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # important!
      - uses: ahmadnassri/action-template-repository-sync@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
